### ISSUE TITLE
Autocomplete not collapsing on click outside of it

### ISSUE THREAD

**Issue by mbacfa** [konsalex/Airport-Autocomplete-JS#8]
If autocomplete is expanded, it remains so unless user selects an option from it or deletes the input.

**Comment by konsalex** [comment]
Fixed ✌️

**Comment by mbacfa** [comment]
Does anything change in how I install/use it? Still not working on my website...
